name: CI Java 17

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Build com Maven
      - name: Build project
        run: mvn -B clean package

      # 4. Rodar testes
      - name: Run tests
        run: mvn test

      # 5. Gerar artefato (JAR)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar